### ISSUE TITLE
Magento 2.2.5 issue with interface

### ISSUE THREAD

**Issue by johncarlson21** [quickshiftin/mage2-ordered-assets#8]
Cannot get extension to work with new Magento 2.2.5

Error in log:

```
[02-Aug-2018 17:58:50 UTC] PHP Fatal error:  Uncaught TypeError: Argument 1 passed to Magento\Framework\View\Page\Config\Renderer::getAssetContentType() must implement interface Magento\Framework\View\Asset\AssetInterface, instance of Quickshiftin\Assetorderer\View\Asset\File given, called in /home/dev2magicmurals/public_html/vendor/magento/framework/View/Page/Config/Renderer.php on line 351 and defined in /home/dev2magicmurals/public_html/vendor/magento/framework/View/Page/Config/Renderer.php:368
Stack trace:
#0 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Page/Config/Renderer.php(351): Magento\Framework\View\Page\Config\Renderer->getAssetContentType(Object(Quickshiftin\Assetorderer\View\Asset\File))
#1 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Page/Config/Renderer.php(239): Magento\Framework\View\Page\Config\Renderer->renderAssetHtml(Object(Magento\Framework\View\Asset\PropertyGroup\Interceptor))
#2 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Page/Config/Renderer.php(226): Magento\Framework\ in /home/dev2magicmurals/public_html/vendor/magento/framework/View/Page/Config/Renderer.php on line 368
```

**Comment by quickshiftin** [comment]
Thanks John, I'll take a look as soon as I can

**Comment by johncarlson21** [comment]
Please do. 

John

**Comment by quickshiftin** [comment]
Hi @johncarlson21,

I don't have an M2 instance setup ATM, nor unit tests for the extension. I have pushed up my best guess at a fix though. It's available through composer via

`composer require quickshiftin/assetorderer:dev-issue-2`

Would you mind giving it a quick try?

**Comment by johncarlson21** [comment]
sure.. give me just a minute..

**Comment by johncarlson21** [comment]
still the same thing:

1 exception(s):
Exception #0 (Magento\Framework\Config\Dom\ValidationException):
Element 'css', attribute 'order': The attribute 'order' is not
allowed.
Line: 31


Exception #0 (Magento\Framework\Config\Dom\ValidationException):
Element 'css', attribute 'order': The attribute 'order' is not
allowed.
Line: 31

#0 /home/dev2magicmurals/public_html/vendor/magento/framework/Config/Dom.php(115):
Magento\Framework\Config\Dom->_initDom('<layout xmlns:x...')
#1 /home/dev2magicmurals/public_html/vendor/magento/framework/ObjectManager/Factory/AbstractFactory.php(111):
Magento\Framework\Config\Dom->__construct('<layout xmlns:x...',
Object(Magento\Framework\App\Arguments\ValidationState), Array, NULL,
'/home/dev2magic...', '%message%\nLine:...')
#2 /home/dev2magicmurals/public_html/vendor/magento/framework/ObjectManager/Factory/Dynamic/Developer.php(66):
Magento\Framework\ObjectManager\Factory\AbstractFactory->createObject('Magento\\Framewo...',
Array)
#3 /home/dev2magicmurals/public_html/vendor/magento/framework/ObjectManager/ObjectManager.php(56):
Magento\Framework\ObjectManager\Factory\Dynamic\Developer->create('Magento\\Framewo...',
Array)
#4 /home/dev2magicmurals/public_html/vendor/magento/framework/Config/DomFactory.php(42):
Magento\Framework\ObjectManager\ObjectManager->create('Magento\\Framewo...',
Array)
#5 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Model/Layout/Update/Validator.php(141):
Magento\Framework\Config\DomFactory->createDom(Array)
#6 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Model/Layout/Merge.php(461):
Magento\Framework\View\Model\Layout\Update\Validator->isValid('<layout
xmlns:x...', 'layout_merged', false)
#7 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Model/Layout/Merge.php(442):
Magento\Framework\View\Model\Layout\Merge->_validateMergedLayout('LAYOUT_frontend...',
'<body>\n   <refe...')
#8 /home/dev2magicmurals/public_html/generated/code/Magento/Framework/View/Model/Layout/Merge/Interceptor.php(193):
Magento\Framework\View\Model\Layout\Merge->load(Array)
#9 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Layout/Builder.php(86):
Magento\Framework\View\Model\Layout\Merge\Interceptor->load()
#10 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Layout/Builder.php(63):
Magento\Framework\View\Layout\Builder->loadLayoutUpdates()
#11 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Layout.php(254):
Magento\Framework\View\Layout\Builder->build()
#12 /home/dev2magicmurals/public_html/vendor/magento/framework/View/Layout.php(876):
Magento\Framework\View\Layout->build()
#13 /home/dev2magicmurals/public_html/generated/code/Magento/Framework/View/Layout/Interceptor.php(414):
Magento\Framework\View\Layout->getBlock('page_content_he...')
#14 /home/dev2magicmurals/public_html/vendor/magento/module-cms/Helper/Page.php(171):
Magento\Framework\View\Layout\Interceptor->getBlock('page_content_he...')
#15 /home/dev2magicmurals/public_html/vendor/magento/module-cms/Controller/Index/Index.php(43):
Magento\Cms\Helper\Page->prepareResultPage(Object(Magento\Cms\Controller\Index\Index\Interceptor),
'ultimo-home-pag...')
#16 /home/dev2magicmurals/public_html/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(24):
Magento\Cms\Controller\Index\Index->execute(NULL)
#17 /home/dev2magicmurals/public_html/vendor/magento/framework/App/Action/Action.php(107):
Magento\Cms\Controller\Index\Index\Interceptor->execute()
#18 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(58):
Magento\Framework\App\Action\Action->dispatch(Object(Magento\Framework\App\Request\Http))
#19 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(138):
Magento\Cms\Controller\Index\Index\Interceptor->___callParent('dispatch',
Array)
#20 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(153):
Magento\Cms\Controller\Index\Index\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#21 /home/dev2magicmurals/public_html/generated/code/Magento/Cms/Controller/Index/Index/Interceptor.php(39):
Magento\Cms\Controller\Index\Index\Interceptor->___callPlugins('dispatch',
Array, Array)
#22 /home/dev2magicmurals/public_html/vendor/magento/framework/App/FrontController.php(55):
Magento\Cms\Controller\Index\Index\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#23 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(58):
Magento\Framework\App\FrontController->dispatch(Object(Magento\Framework\App\Request\Http))
#24 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(138):
Magento\Framework\App\FrontController\Interceptor->___callParent('dispatch',
Array)
#25 /home/dev2magicmurals/public_html/vendor/magento/module-store/App/FrontController/Plugin/RequestPreprocessor.php(94):
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#26 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(135):
Magento\Store\App\FrontController\Plugin\RequestPreprocessor->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor),
Object(Closure), Object(Magento\Framework\App\Request\Http))
#27 /home/dev2magicmurals/public_html/vendor/magento/module-page-cache/Model/App/FrontController/BuiltinPlugin.php(73):
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#28 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(135):
Magento\PageCache\Model\App\FrontController\BuiltinPlugin->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor),
Object(Closure), Object(Magento\Framework\App\Request\Http))
#29 /home/dev2magicmurals/public_html/app/code/Infortis/Cgen/Plugin/Magento/Framework/App/FrontController.php(32):
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#30 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(135):
Infortis\Cgen\Plugin\Magento\Framework\App\FrontController->aroundDispatch(Object(Magento\Framework\App\FrontController\Interceptor),
Object(Closure), Object(Magento\Framework\App\Request\Http))
#31 /home/dev2magicmurals/public_html/vendor/magento/framework/Interception/Interceptor.php(153):
Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Request\Http))
#32 /home/dev2magicmurals/public_html/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26):
Magento\Framework\App\FrontController\Interceptor->___callPlugins('dispatch',
Array, NULL)
#33 /home/dev2magicmurals/public_html/vendor/magento/framework/App/Http.php(135):
Magento\Framework\App\FrontController\Interceptor->dispatch(Object(Magento\Framework\App\Request\Http))
#34 /home/dev2magicmurals/public_html/generated/code/Magento/Framework/App/Http/Interceptor.php(24):
Magento\Framework\App\Http->launch()
#35 /home/dev2magicmurals/public_html/vendor/magento/framework/App/Bootstrap.php(256):
Magento\Framework\App\Http\Interceptor->launch()
#36 /home/dev2magicmurals/public_html/index.php(39):
Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#37 {main}

**Comment by quickshiftin** [comment]
Thanks for checking! Actually, that looks like a totally different error now. So perhaps a step in the right direction, or in the opposite. I'll try to get an M2 setup going soon so I can properly test.

**Comment by quickshiftin** [comment]
Hi @johncarlson21 I dove back into the code and did a pretty big update. Can you give version 1.1.0 a try when you have a chance?
